name: project_environment
dependencies:
- python=3.6.2
- psutil=5.3
- pip:
    # Required packages for AzureML execution, history, and data preparation.
  - azureml-sdk
  - https://download.pytorch.org/whl/cpu/torch-1.1.0-cp36-cp36m-linux_x86_64.whl
  - https://download.pytorch.org/whl/cpu/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl
  - Pillow
  - pandas==0.23.1
  - numpy==1.14.5